name: client
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  http: ^1.0.0
  get_it: ^7.6.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  stream_transform: ^2.1.0
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.0.2
  asuka: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  bloc_test: ^9.1.2


flutter:
  uses-material-design: true

  assets:
    - assets/logo_google.png
    - .env
